version: '3.8'

services:
  merch-api:
    build: ../
    hostname: merch-api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPasSL
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ../.aspnet/https:/https:ro