version: '3.8'

services:

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    ports:
      - "5070:5000"
      - "5072:5002"
    networks:
      - ozon-network  
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=stock-api-db;Port=5432;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db
      - redis

  merch-api-db:
    image: postgres:latest
    ports:
      - "5424:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchApiPassword
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - merch-api-db:/var/lib/postgresql/data

  stock-api-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api
    command: "-c log_statement=all"
    networks:
      - ozon-network  
    volumes:
      - stock-api-db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ozon-network  
    hostname: redis

networks:
  ozon-network:
    driver: bridge

volumes:
  ozon-volume:
    driver: local
  stock-api-db:
    driver: local
  merch-api-db:
    driver: local