version: '3.8'

services:
  merch-api:
    build:
      context: ../
      dockerfile: ./Dockerfile
    hostname: merch-api
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5004:5004"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPasSL
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DatabaseConnectionOptions__ConnectionString=Host=host.docker.internal;Port=5425;Database=merch-api;Username=postgres;Password=merchApiPassword;
    volumes:
      - ../.aspnet/https:/https:ro
    depends_on:
      - merch-api-db
      
  merch-api-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchApiPassword
      POSTGRES_DB: merch-api

